In [1]:
import xgboost as XGBClassifier

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df = pd.read_csv('train.csv')

In [4]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [11]:
df['LotFrontage'].isna().any()

True

In [12]:
df.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
df.dropna(axis=1).columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotArea', 'Street', 'LotShape',
       'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood',
       'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl',
       'Exterior1st', 'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'GarageCars', 'GarageArea', 'PavedDrive',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [3]:
mat = df.corr()

In [4]:
mat.shape

(38, 38)

In [5]:
mat1 = mat.iloc[-1,:]

In [8]:
mat

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
Id,1.000000,0.011156,-0.010601,-0.033226,-0.028365,0.012609,-0.012713,-0.021998,-0.050298,-0.005024,...,-0.029643,-0.000477,0.002889,-0.046635,0.001330,0.057044,-0.006242,0.021172,0.000712,-0.021917
MSSubClass,0.011156,1.000000,-0.386347,-0.139781,0.032628,-0.059316,0.027850,0.040581,0.022936,-0.069836,...,-0.012579,-0.006100,-0.012037,-0.043825,-0.026030,0.008283,-0.007683,-0.013585,-0.021407,-0.084284
LotFrontage,-0.010601,-0.386347,1.000000,0.426095,0.251646,-0.059213,0.123349,0.088866,0.193458,0.233633,...,0.088521,0.151972,0.010700,0.070029,0.041383,0.206167,0.003368,0.011200,0.007450,0.351799
LotArea,-0.033226,-0.139781,0.426095,1.000000,0.105806,-0.005636,0.014228,0.013788,0.104160,0.214103,...,0.171698,0.084774,-0.018340,0.020423,0.043160,0.077672,0.038068,0.001205,-0.014261,0.263843
OverallQual,-0.028365,0.032628,0.251646,0.105806,1.000000,-0.091932,0.572323,0.550684,0.411876,0.239666,...,0.238923,0.308819,-0.113937,0.030371,0.064886,0.065166,-0.031406,0.070815,-0.027347,0.790982
OverallCond,0.012609,-0.059316,-0.059213,-0.005636,-0.091932,1.000000,-0.375983,0.073741,-0.128101,-0.046231,...,-0.003334,-0.032589,0.070356,0.025504,0.054811,-0.001985,0.068777,-0.003511,0.043950,-0.077856
YearBuilt,-0.012713,0.027850,0.123349,0.014228,0.572323,-0.375983,1.000000,0.592855,0.315707,0.249503,...,0.224880,0.188686,-0.387268,0.031355,-0.050364,0.004950,-0.034383,0.012398,-0.013618,0.522897
YearRemodAdd,-0.021998,0.040581,0.088866,0.013788,0.550684,0.073741,0.592855,1.000000,0.179618,0.128451,...,0.205726,0.226298,-0.193919,0.045286,-0.038740,0.005829,-0.010286,0.021490,0.035743,0.507101
MasVnrArea,-0.050298,0.022936,0.193458,0.104160,0.411876,-0.128101,0.315707,0.179618,1.000000,0.264736,...,0.159718,0.125703,-0.110204,0.018796,0.061466,0.011723,-0.029815,-0.005965,-0.008201,0.477493
BsmtFinSF1,-0.005024,-0.069836,0.233633,0.214103,0.239666,-0.046231,0.249503,0.128451,0.264736,1.000000,...,0.204306,0.111761,-0.102303,0.026451,0.062021,0.140491,0.003571,-0.015727,0.014359,0.386420
BsmtFinSF2,-0.005968,-0.065649,0.049900,0.111170,-0.059119,0.040229,-0.049107,-0.067759,-0.072319,-0.050117,...,0.067898,0.003093,0.036543,-0.029993,0.088871,0.041709,0.004940,-0.015211,0.031706,-0.011378
BsmtUnfSF,-0.007940,-0.140759,0.132644,-0.002618,0.308159,-0.136841,0.149040,0.181133,0.114442,-0.495251,...,-0.005316,0.129005,-0.002538,0.020764,-0.012579,-0.035092,-0.023837,0.034888,-0.041258,0.214479
TotalBsmtSF,-0.015415,-0.238518,0.392075,0.260833,0.537808,-0.171098,0.391452,0.291066,0.363936,0.522396,...,0.232019,0.247264,-0.095478,0.037384,0.084489,0.126053,-0.018479,0.013196,-0.014969,0.613581
1stFlrSF,0.010496,-0.251758,0.457181,0.299475,0.476224,-0.144203,0.281986,0.240379,0.344501,0.445863,...,0.235459,0.211671,-0.065292,0.056104,0.088758,0.131525,-0.021096,0.031372,-0.013604,0.605852
2ndFlrSF,0.005590,0.307886,0.080177,0.050986,0.295493,0.028942,0.010308,0.140024,0.174561,-0.137079,...,0.092165,0.208026,0.061989,-0.024358,0.040606,0.081487,0.016197,0.035164,-0.028700,0.319334
LowQualFinSF,-0.044230,0.046474,0.038469,0.004779,-0.030429,0.025494,-0.183784,-0.062419,-0.069071,-0.064503,...,-0.025444,0.018251,0.061081,-0.004296,0.026799,0.062157,-0.003793,-0.022174,-0.028921,-0.025606
GrLivArea,0.008273,0.074853,0.402797,0.263116,0.593007,-0.079686,0.199010,0.287389,0.390857,0.208171,...,0.247433,0.330224,0.009113,0.020643,0.101510,0.170205,-0.002416,0.050240,-0.036526,0.708624
BsmtFullBath,0.002289,0.003491,0.100949,0.158155,0.111098,-0.054942,0.187599,0.119470,0.085310,0.649212,...,0.175315,0.067341,-0.049911,-0.000106,0.023148,0.067616,-0.023047,-0.025361,0.067049,0.227122
BsmtHalfBath,-0.020155,-0.002333,-0.007234,0.048046,-0.040150,0.117821,-0.038162,-0.012337,0.026673,0.067418,...,0.040161,-0.025324,-0.008555,0.035114,0.032121,0.020025,-0.007367,0.032873,-0.046524,-0.016844
FullBath,0.005587,0.131608,0.198769,0.126031,0.550600,-0.194149,0.468271,0.439046,0.276833,0.058543,...,0.187703,0.259977,-0.115093,0.035353,-0.008106,0.049604,-0.014290,0.055872,-0.019669,0.560664
HalfBath,0.006784,0.177354,0.053532,0.014259,0.273458,-0.060769,0.242656,0.183331,0.201444,0.004262,...,0.108080,0.199740,-0.095317,-0.004972,0.072426,0.022381,0.001290,-0.009050,-0.010269,0.284108
BedroomAbvGr,0.037719,-0.023438,0.263170,0.119690,0.101676,0.012980,-0.070651,-0.040581,0.102821,-0.107355,...,0.046854,0.093810,0.041570,-0.024478,0.044300,0.070703,0.007767,0.046544,-0.036014,0.168213
KitchenAbvGr,0.002951,0.281721,-0.006069,-0.017784,-0.183882,-0.087001,-0.174800,-0.149598,-0.037610,-0.081007,...,-0.090130,-0.070091,0.037312,-0.024600,-0.051613,-0.014525,0.062341,0.026589,0.031687,-0.135907
TotRmsAbvGrd,0.027239,0.040380,0.352096,0.190015,0.427452,-0.057583,0.095589,0.191740,0.280682,0.044316,...,0.165984,0.234192,0.004151,-0.006683,0.059383,0.083757,0.024763,0.036907,-0.034516,0.533723
Fireplaces,-0.019772,-0.045569,0.266639,0.271364,0.396765,-0.023820,0.147716,0.112581,0.249070,0.260011,...,0.200019,0.169405,-0.024822,0.011257,0.184530,0.095074,0.001409,0.046357,-0.024096,0.466929
GarageYrBlt,0.000072,0.085072,0.070250,-0.024947,0.547766,-0.324297,0.825667,0.642277,0.252691,0.153484,...,0.224577,0.228425,-0.297003,0.023544,-0.075418,-0.014501,-0.032417,0.005337,-0.001014,0.486362
GarageCars,0.016570,-0.040110,0.285691,0.154871,0.600671,-0.185758,0.537850,0.420622,0.364204,0.224054,...,0.226342,0.213569,-0.151434,0.035765,0.050494,0.020934,-0.043080,0.040522,-0.039117,0.640409
GarageArea,0.017634,-0.098672,0.344997,0.180403,0.562022,-0.151521,0.478954,0.371600,0.373066,0.296970,...,0.224666,0.241435,-0.121777,0.035087,0.051412,0.061047,-0.027400,0.027974,-0.027378,0.623431
WoodDeckSF,-0.029643,-0.012579,0.088521,0.171698,0.238923,-0.003334,0.224880,0.205726,0.159718,0.204306,...,1.000000,0.058661,-0.125989,-0.032771,-0.074181,0.073378,-0.009551,0.021011,0.022270,0.324413
OpenPorchSF,-0.000477,-0.006100,0.151972,0.084774,0.308819,-0.032589,0.188686,0.226298,0.125703,0.111761,...,0.058661,1.000000,-0.093079,-0.005842,0.074304,0.060762,-0.018584,0.071255,-0.057619,0.315856
EnclosedPorch,0.002889,-0.012037,0.010700,-0.018340,-0.113937,0.070356,-0.387268,-0.193919,-0.110204,-0.102303,...,-0.125989,-0.093079,1.000000,-0.037305,-0.082864,0.054203,0.018361,-0.028887,-0.009916,-0.128578
3SsnPorch,-0.046635,-0.043825,0.070029,0.020423,0.030371,0.025504,0.031355,0.045286,0.018796,0.026451,...,-0.032771,-0.005842,-0.037305,1.000000,-0.031436,-0.007992,0.000354,0.029474,0.018645,0.044584
ScreenPorch,0.001330,-0.026030,0.041383,0.043160,0.064886,0.054811,-0.050364,-0.038740,0.061466,0.062021,...,-0.074181,0.074304,-0.082864,-0.031436,1.000000,0.051307,0.031946,0.023217,0.010694,0.111447
PoolArea,0.057044,0.008283,0.206167,0.077672,0.065166,-0.001985,0.004950,0.005829,0.011723,0.140491,...,0.073378,0.060762,0.054203,-0.007992,0.051307,1.000000,0.029669,-0.033737,-0.059689,0.092404
MiscVal,-0.006242,-0.007683,0.003368,0.038068,-0.031406,0.068777,-0.034383,-0.010286,-0.029815,0.003571,...,-0.009551,-0.018584,0.018361,0.000354,0.031946,0.029669,1.000000,-0.006495,0.004906,-0.021190
MoSold,0.021172,-0.013585,0.011200,0.001205,0.070815,-0.003511,0.012398,0.021490,-0.005965,-0.015727,...,0.021011,0.071255,-0.028887,0.029474,0.023217,-0.033737,-0.006495,1.000000,-0.145721,0.046432
YrSold,0.000712,-0.021407,0.007450,-0.014261,-0.027347,0.043950,-0.013618,0.035743,-0.008201,0.014359,...,0.022270,-0.057619,-0.009916,0.018645,0.010694,-0.059689,0.004906,-0.145721,1.000000,-0.028923
SalePrice,-0.021917,-0.084284,0.351799,0.263843,0.790982,-0.077856,0.522897,0.507101,0.477493,0.386420,...,0.324413,0.315856,-0.128578,0.044584,0.111447,0.092404,-0.021190,0.046432,-0.028923,1.000000

In [11]:
mat1[mat1>.5][:-1:]

OverallQual     0.790982
YearBuilt       0.522897
YearRemodAdd    0.507101
TotalBsmtSF     0.613581
1stFlrSF        0.605852
GrLivArea       0.708624
FullBath        0.560664
TotRmsAbvGrd    0.533723
GarageCars      0.640409
GarageArea      0.623431
Name: SalePrice, dtype: float64

In [6]:
cols = mat1[mat1>.5][:-1:].index

In [29]:
cols

Index(['OverallQual', 'YearBuilt', 'YearRemodAdd', 'TotalBsmtSF', '1stFlrSF',
       'GrLivArea', 'FullBath', 'TotRmsAbvGrd', 'GarageCars', 'GarageArea'],
      dtype='object')

In [7]:
X = df[cols]

In [33]:
X.head()

,OverallQual,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageCars,GarageArea
0,7,2003,2003,856,856,1710,2,8,2,548
1,6,1976,1976,1262,1262,1262,2,6,2,460
2,7,2001,2002,920,920,1786,2,6,2,608
3,7,1915,1970,756,961,1717,1,7,3,642
4,8,2000,2000,1145,1145,2198,2,9,3,836

In [14]:
X.shape

(1460, 10)

In [8]:
Y = df.iloc[:,-1]

In [16]:
Y.shape

(1460,)

In [17]:
X.isna().any()

OverallQual     False
YearBuilt       False
YearRemodAdd    False
TotalBsmtSF     False
1stFlrSF        False
GrLivArea       False
FullBath        False
TotRmsAbvGrd    False
GarageCars      False
GarageArea      False
dtype: bool

In [18]:
Y.isna().any()

False

In [41]:
X.head()

,OverallQual,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageCars,GarageArea
0,7,2003,2003,856,856,1710,2,8,2,548
1,6,1976,1976,1262,1262,1262,2,6,2,460
2,7,2001,2002,920,920,1786,2,6,2,608
3,7,1915,1970,756,961,1717,1,7,3,642
4,8,2000,2000,1145,1145,2198,2,9,3,836

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
Model1 = LinearRegression()

In [33]:
from sklearn.preprocessing import StandardScaler
SS = StandardScaler()
X_scaled = SS.fit_transform(X)
Model_scaled = LinearRegression()
Model_scaled.fit(X_scaled,Y)
Model_scaled.score(X_scaled,Y)

0.7736928402773303

In [34]:
Y_predict = Model_scaled.predict(X_scaled)
mean_squared_log_error(Y,Y_predict)

ValueError: Mean Squared Logarithmic Error cannot be used when targets contain negative values.

In [11]:
Model1.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
Model1.score(X,Y)

0.7736928402773304

In [13]:
from sklearn.metrics import mean_squared_log_error

In [36]:
mean_squared_log_error(Y,Y_predict)

0.28893641509709067

In [19]:
Y_predict = Model1.predict(X)

In [35]:
Y_predict = np.where(Y_predict<0,0,Y_predict)

In [19]:
df_test = pd.read_csv('test.csv')

In [48]:
df_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [20]:
df_test = df_test[cols]

In [21]:
df_test.shape

(1459, 10)

In [51]:
cols

Index(['OverallQual', 'YearBuilt', 'YearRemodAdd', 'TotalBsmtSF', '1stFlrSF',
       'GrLivArea', 'FullBath', 'TotRmsAbvGrd', 'GarageCars', 'GarageArea'],
      dtype='object')

In [52]:
X.shape

(1460, 10)

In [53]:
Y_final = Model1.predict(df_test)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [27]:
df_test.isna().any()

OverallQual     False
YearBuilt       False
YearRemodAdd    False
TotalBsmtSF     False
1stFlrSF        False
GrLivArea       False
FullBath        False
TotRmsAbvGrd    False
GarageCars       True
GarageArea       True
dtype: bool

In [23]:
df_test['TotalBsmtSF'].fillna(value=df_test['TotalBsmtSF'].mean(),inplace = True)

In [63]:
df_test['GarageCars'].mode()

0    2.0
dtype: float64

In [24]:
df_test['GarageCars'].fillna(value=df_test['GarageCars'].mode(),inplace = True)

In [72]:
df_test.isna().any().sum()

2

In [73]:
df_test['GarageCars'].isna().any().sum()

1

In [79]:
sum(df_test['GarageCars'].isna())

1

In [26]:
df_test[df_test['GarageCars'].isna()==True]['GarageCars']=2.0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [83]:
df_test[df_test['GarageCars'].isna()==True]

,OverallQual,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageCars,GarageArea
1116,5,1923,1999,859.0,942,1828,2,6,NaN,NaN

In [28]:
df_test.iloc[1116]['GarageCars']=2.0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [86]:
df_test.iloc[1116]

OverallQual        5.0
YearBuilt       1923.0
YearRemodAdd    1999.0
TotalBsmtSF      859.0
1stFlrSF         942.0
GrLivArea       1828.0
FullBath           2.0
TotRmsAbvGrd       6.0
GarageCars         NaN
GarageArea         NaN
Name: 1116, dtype: float64

In [29]:
df_test1 = df_test.copy()

In [30]:
df_test1.iloc[1116]['GarageCars']=2.0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
df_test1['GarageCars'].fillna(value=2.0,inplace = True)

In [32]:
df_test1.iloc[1116]

OverallQual        5.0
YearBuilt       1923.0
YearRemodAdd    1999.0
TotalBsmtSF      859.0
1stFlrSF         942.0
GrLivArea       1828.0
FullBath           2.0
TotRmsAbvGrd       6.0
GarageCars         2.0
GarageArea         NaN
Name: 1116, dtype: float64

In [97]:
df_test1['GarageArea'].median()

480.0

In [33]:
df_test1['GarageArea'].fillna(value=480.0,inplace = True)

In [34]:
df_test1.isna().any()

OverallQual     False
YearBuilt       False
YearRemodAdd    False
TotalBsmtSF     False
1stFlrSF        False
GrLivArea       False
FullBath        False
TotRmsAbvGrd    False
GarageCars      False
GarageArea      False
dtype: bool

In [100]:
Y_final = Model1.predict(df_test1)

In [101]:
Y_final

array([110135.92110887, 159059.96019542, 169683.67729304, ...,
       156695.01584383, 111786.59984412, 241008.24266205])

In [103]:
df_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [104]:
df_test1.head()

,OverallQual,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageCars,GarageArea
0,5,1961,1961,882.0,896,896,1,5,1.0,730.0
1,6,1958,1958,1329.0,1329,1329,1,6,1.0,312.0
2,5,1997,1998,928.0,928,1629,2,6,2.0,482.0
3,6,1998,1998,926.0,926,1604,2,7,2.0,470.0
4,8,1992,1992,1280.0,1280,1280,2,5,2.0,506.0

In [105]:
df_test['YearBuilt']==df_test1['YearBuilt']

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
        ...
1429    True
1430    True
1431    True
1432    True
1433    True
1434    True
1435    True
1436    True
1437    True
1438    True
1439    True
1440    True
1441    True
1442    True
1443    True
1444    True
1445    True
1446    True
1447    True
1448    True
1449    True
1450    True
1451    True
1452    True
1453    True
1454    True
1455    True
1456    True
1457    True
1458    True
Name: YearBuilt, Length: 1459, dtype: bool

In [109]:
output = pd.concat(df_test.iloc[:,[0]],Y_final)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

In [112]:
df_test['SalePrice']=Y_final

In [114]:
df_final = df_test[['Id','SalePrice']]

In [115]:
df_final.shape

(1459, 2)

In [117]:
df_final.to_csv('output1.csv',index=False)     #Score = 0.7736928402773304

Using XGBClassifier

In [37]:
#from xgboost import XGBClassifier
xgb1 = XGBClassifier.XGBClassifier()
xgb1.fit(X,Y)
Y_xgb = xgb1.predict(df_test1)
df_xgb['Id'] = df_test['Id']
df_xgb['SalePrice'] = Y_xgb
df_xgb

KeyError: 'Id'

In [124]:
X.shape,Y.shape,df_test1.shape,df_test.shape

((1460, 10), (1460,), (1459, 10), (1459, 81))

In [38]:
Y_xgb

array([110000, 163000, 181000, ..., 132000, 132500, 219500], dtype=int64)

In [39]:
df_test

,OverallQual,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageCars,GarageArea
0,5,1961,1961,882.0,896,896,1,5,1.0,730.0
1,6,1958,1958,1329.0,1329,1329,1,6,1.0,312.0
2,5,1997,1998,928.0,928,1629,2,6,2.0,482.0
3,6,1998,1998,926.0,926,1604,2,7,2.0,470.0
4,8,1992,1992,1280.0,1280,1280,2,5,2.0,506.0
5,6,1993,1994,763.0,763,1655,2,7,2.0,440.0
6,6,1992,2007,1168.0,1187,1187,2,6,2.0,420.0
7,6,1998,1998,789.0,789,1465,2,7,2.0,393.0
8,7,1990,1990,1300.0,1341,1341,1,5,2.0,506.0
9,4,1970,1970,882.0,882,882,1,4,2.0,525.0
10,7,1999,1999,1405.0,1337,1337,2,5,2.0,511.0
11,6,1971,1971,483.0,483,987,1,5,1.0,264.0
12,5,1971,1971,525.0,525,1092,1,6,1.0,320.0
13,6,1975,1975,855.0,855,1456,2,6,2.0,440.0
14,7,1975,1975,836.0,836,836,1,4,1.0,308.0
15,9,2009,2010,1590.0,1627,2334,2,10,3.0,751.0
16,8,2009,2010,1544.0,1544,1544,2,7,3.0,868.0
17,9,2005,2005,1698.0,1698,1698,2,7,3.0,730.0
18,8,2005,2006,1822.0,1822,1822,2,8,3.0,678.0
19,9,2003,2004,2846.0,2696,2696,2,10,3.0,958.0
20,8,2002,2002,1671.0,1687,2250,2,7,3.0,756.0
21,8,2006,2006,1370.0,1370,1370,2,6,2.0,484.0
22,6,2005,2005,1324.0,1324,1324,2,6,2.0,430.0
23,7,2006,2006,1145.0,1145,1145,2,6,2.0,437.0
24,7,2004,2004,384.0,744,1374,2,7,2.0,400.0
25,7,2004,2004,847.0,847,1733,2,7,2.0,433.0
26,8,1998,1998,1629.0,1645,2475,2,7,3.0,962.0
27,8,2005,2006,1595.0,1595,1595,2,6,3.0,880.0
28,7,2009,2010,1218.0,1218,1218,2,4,2.0,676.0
29,6,2005,2005,1468.0,1468,1468,2,6,2.0,528.0
...,...,...,...,...,...,...,...,...,...,...
1429,4,1925,1950,641.0,641,641,1,4,1.0,272.0
1430,6,1957,1957,967.0,967,1638,2,6,1.0,384.0
1431,3,1945,1950,0.0,729,729,1,5,0.0,0.0
1432,5,1951,1951,660.0,1060,1396,2,8,0.0,0.0
1433,3,1916,1950,216.0,576,936,1,6,0.0,0.0
1434,8,2005,2006,1573.0,1778,1778,2,5,2.0,495.0
1435,8,2004,2005,1594.0,1646,1646,2,5,2.0,525.0
1436,6,1979,1979,1625.0,1625,1625,2,6,2.0,576.0
1437,6,1978,1978,1664.0,1664,1664,2,10,2.0,616.0
1438,8,2001,2001,1491.0,1491,1491,2,7,2.0,490.0
1439,6,1975,1975,1128.0,1210,1210,2,6,2.0,528.0
1440,6,1958,1958,1632.0,1650,1650,1,6,2.0,518.0
1441,6,2000,2000,1381.0,1403,1403,2,5,2.0,470.0
1442,8,2005,2006,1728.0,1960,1960,2,8,3.0,714.0
1443,9,2005,2006,1838.0,1838,1838,2,9,3.0,682.0
1444,1,1951,1951,0.0,1600,1600,1,6,1.0,270.0
1445,7,1997,1997,1288.0,1368,1368,2,8,4.0,784.0
1446,5,1977,1977,264.0,616,1304,1,5,1.0,336.0
1447,5,1968,2003,864.0,874,874,1,5,1.0,288.0
1448,5,1970,1970,1652.0,1652,1652,2,8,3.0,928.0
1449,4,1970,1970,630.0,630,630,1,3,0.0,0.0
1450,4,1972,1972,546.0,546,1092,1,5,1.0,253.0
1451,5,1969,1979,1104.0,1360,1360,1,8,1.0,336.0
1452,4,1970,1970,546.0,546,1092,1,5,1.0,286.0
1453,4,1970,1970,546.0,546,1092,1,5,0.0,0.0
1454,4,1970,1970,546.0,546,1092,1,5,0.0,0.0
1455,4,1970,1970,546.0,546,1092,1,6,1.0,286.0
1456,5,1960,1996,1224.0,1224,1224,1,7,2.0,576.0
1457,5,1992,1992,912.0,970,970,1,6,0.0,0.0
1458,7,1993,1994,996.0,996,2000,2,9,3.0,650.0

In [41]:
df_xgb = pd.read_csv('test.csv',usecols=['Id'])

In [42]:
df_xgb

        Id
0     1461
1     1462
2     1463
3     1464
4     1465
5     1466
6     1467
7     1468
8     1469
9     1470
10    1471
11    1472
12    1473
13    1474
14    1475
15    1476
16    1477
17    1478
18    1479
19    1480
20    1481
21    1482
22    1483
23    1484
24    1485
25    1486
26    1487
27    1488
28    1489
29    1490
...    ...
1429  2890
1430  2891
1431  2892
1432  2893
1433  2894
1434  2895
1435  2896
1436  2897
1437  2898
1438  2899
1439  2900
1440  2901
1441  2902
1442  2903
1443  2904
1444  2905
1445  2906
1446  2907
1447  2908
1448  2909
1449  2910
1450  2911
1451  2912
1452  2913
1453  2914
1454  2915
1455  2916
1456  2917
1457  2918
1458  2919

[1459 rows x 1 columns]

In [43]:
df_xgb['SalePrice'] = Y_xgb
df_xgb

        Id  SalePrice
0     1461     110000
1     1462     163000
2     1463     181000
3     1464     181000
4     1465     179200
5     1466     178000
6     1467     187500
7     1468     180000
8     1469     180000
9     1470     129000
10    1471     181000
11    1472      89500
12    1473      88000
13    1474     148500
14    1475     170000
15    1476     315000
16    1477     205000
17    1478     275000
18    1479     320000
19    1480     385000
20    1481     350000
21    1482     202500
22    1483     176000
23    1484     140000
24    1485     178000
25    1486     225000
26    1487     340000
27    1488     232000
28    1489     194000
29    1490     215000
...    ...        ...
1429  2890      81000
1430  2891     127500
1431  2892      80000
1432  2893     102000
1433  2894      55000
1434  2895     275000
1435  2896     275000
1436  2897     190000
1437  2898     171000
1438  2899     215000
1439  2900     165000
1440  2901     167000
1441  2902     181000
1442  2903     315000
1443  2904     320000
1444  2905      82000
1445  2906     202500
1446  2907     115000
1447  2908     130000
1448  2909     110000
1449  2910      84500
1450  2911     118000
1451  2912     158000
1452  2913      88000
1453  2914      88000
1454  2915      88000
1455  2916      88000
1456  2917     132000
1457  2918     132500
1458  2919     219500

[1459 rows x 2 columns]

In [45]:
df_xgb.to_csv('output2.csv',index=False)

In [46]:
df_xgb.shape

(1459, 2)

In [50]:
mat1[mat1>.4][:-1:]

OverallQual     0.790982
YearBuilt       0.522897
YearRemodAdd    0.507101
MasVnrArea      0.477493
TotalBsmtSF     0.613581
1stFlrSF        0.605852
GrLivArea       0.708624
FullBath        0.560664
TotRmsAbvGrd    0.533723
Fireplaces      0.466929
GarageYrBlt     0.486362
GarageCars      0.640409
GarageArea      0.623431
Name: SalePrice, dtype: float64

In [53]:
cols = mat1[mat1>.4][:-1:].index

In [83]:
cols.append('SalePrice')

In [84]:
cols

['OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'TotalBsmtSF',
 '1stFlrSF',
 'GrLivArea',
 'FullBath',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'SalePrice']

In [85]:
df1 = pd.read_csv('train.csv')

In [86]:
X = df1[cols]

In [59]:
X.isna().any()

OverallQual     False
YearBuilt       False
YearRemodAdd    False
MasVnrArea       True
TotalBsmtSF     False
1stFlrSF        False
GrLivArea       False
FullBath        False
TotRmsAbvGrd    False
Fireplaces      False
GarageYrBlt      True
GarageCars      False
GarageArea      False
dtype: bool

In [87]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 14 columns):
OverallQual     1460 non-null int64
YearBuilt       1460 non-null int64
YearRemodAdd    1460 non-null int64
MasVnrArea      1452 non-null float64
TotalBsmtSF     1460 non-null int64
1stFlrSF        1460 non-null int64
GrLivArea       1460 non-null int64
FullBath        1460 non-null int64
TotRmsAbvGrd    1460 non-null int64
Fireplaces      1460 non-null int64
GarageYrBlt     1379 non-null float64
GarageCars      1460 non-null int64
GarageArea      1460 non-null int64
SalePrice       1460 non-null int64
dtypes: float64(2), int64(12)
memory usage: 159.8 KB

In [64]:
X['GarageYrBlt'].value_counts()

2005.0    65
2006.0    59
2004.0    53
2003.0    50
2007.0    49
1977.0    35
1998.0    31
1999.0    30
2008.0    29
1976.0    29
2000.0    27
2002.0    26
1968.0    26
1950.0    24
1993.0    22
2009.0    21
1965.0    21
1966.0    21
1962.0    21
1958.0    21
2001.0    20
1996.0    20
1957.0    20
1970.0    20
1960.0    19
1997.0    19
1978.0    19
1954.0    19
1974.0    18
1994.0    18
          ..
1922.0     5
1936.0     5
1916.0     5
1931.0     4
1945.0     4
1935.0     4
1928.0     4
1946.0     4
1982.0     4
1938.0     3
1921.0     3
1924.0     3
1910.0     3
1952.0     3
1932.0     3
2010.0     3
1923.0     3
1937.0     2
1934.0     2
1918.0     2
1947.0     2
1929.0     2
1914.0     2
1915.0     2
1942.0     2
1908.0     1
1927.0     1
1933.0     1
1900.0     1
1906.0     1
Name: GarageYrBlt, Length: 97, dtype: int64

In [65]:
X['MasVnrArea'].value_counts()

0.0       861
72.0        8
180.0       8
108.0       8
120.0       7
16.0        7
80.0        6
200.0       6
106.0       6
340.0       6
170.0       5
132.0       5
360.0       5
84.0        5
320.0       5
100.0       4
196.0       4
246.0       4
216.0       4
160.0       4
183.0       4
178.0       4
270.0       4
300.0       4
210.0       4
268.0       4
252.0       4
168.0       4
336.0       4
220.0       4
         ...
14.0        1
53.0        1
24.0        1
127.0       1
365.0       1
115.0       1
562.0       1
259.0       1
378.0       1
219.0       1
161.0       1
247.0       1
109.0       1
278.0       1
375.0       1
225.0       1
604.0       1
762.0       1
290.0       1
299.0       1
202.0       1
731.0       1
167.0       1
309.0       1
1129.0      1
651.0       1
337.0       1
415.0       1
293.0       1
621.0       1
Name: MasVnrArea, Length: 327, dtype: int64

In [67]:
sum(X['GarageYrBlt'].isna())

81

In [88]:
X['GarageYrBlt'].fillna(value=2005,inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [89]:
sum(X['GarageYrBlt'].isna())

0

In [73]:
X.isna().any()

OverallQual     False
YearBuilt       False
YearRemodAdd    False
MasVnrArea       True
TotalBsmtSF     False
1stFlrSF        False
GrLivArea       False
FullBath        False
TotRmsAbvGrd    False
Fireplaces      False
GarageYrBlt     False
GarageCars      False
GarageArea      False
dtype: bool

In [90]:
X.dropna(inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [91]:
X.isna().any()

OverallQual     False
YearBuilt       False
YearRemodAdd    False
MasVnrArea      False
TotalBsmtSF     False
1stFlrSF        False
GrLivArea       False
FullBath        False
TotRmsAbvGrd    False
Fireplaces      False
GarageYrBlt     False
GarageCars      False
GarageArea      False
SalePrice       False
dtype: bool

In [92]:
X.columns

Index(['OverallQual', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'TotalBsmtSF',
       '1stFlrSF', 'GrLivArea', 'FullBath', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'SalePrice'],
      dtype='object')

In [93]:
import xgboost as xgb

In [94]:
model2 = xgb.XGBClassifier()

In [96]:
model2.fit(X.iloc[:,:-1],X.iloc[:,-1])

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [95]:
X.iloc[:,:-1]

,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea
0,7,2003,2003,196.0,856,856,1710,2,8,0,2003.0,2,548
1,6,1976,1976,0.0,1262,1262,1262,2,6,1,1976.0,2,460
2,7,2001,2002,162.0,920,920,1786,2,6,1,2001.0,2,608
3,7,1915,1970,0.0,756,961,1717,1,7,1,1998.0,3,642
4,8,2000,2000,350.0,1145,1145,2198,2,9,1,2000.0,3,836
5,5,1993,1995,0.0,796,796,1362,1,5,0,1993.0,2,480
6,8,2004,2005,186.0,1686,1694,1694,2,7,1,2004.0,2,636
7,7,1973,1973,240.0,1107,1107,2090,2,7,2,1973.0,2,484
8,7,1931,1950,0.0,952,1022,1774,2,8,2,1931.0,2,468
9,5,1939,1950,0.0,991,1077,1077,1,5,2,1939.0,1,205
10,5,1965,1965,0.0,1040,1040,1040,1,5,0,1965.0,1,384
11,9,2005,2006,286.0,1175,1182,2324,3,11,2,2005.0,3,736
12,5,1962,1962,0.0,912,912,912,1,4,0,1962.0,1,352
13,7,2006,2007,306.0,1494,1494,1494,2,7,1,2006.0,3,840
14,6,1960,1960,212.0,1253,1253,1253,1,5,1,1960.0,1,352
15,7,1929,2001,0.0,832,854,854,1,5,0,1991.0,2,576
16,6,1970,1970,180.0,1004,1004,1004,1,5,1,1970.0,2,480
17,4,1967,1967,0.0,0,1296,1296,2,6,0,1967.0,2,516
18,5,2004,2004,0.0,1114,1114,1114,1,6,0,2004.0,2,576
19,5,1958,1965,0.0,1029,1339,1339,1,6,0,1958.0,1,294
20,8,2005,2006,380.0,1158,1158,2376,3,9,1,2005.0,3,853
21,7,1930,1950,0.0,637,1108,1108,1,6,1,1930.0,1,280
22,8,2002,2002,281.0,1777,1795,1795,2,7,1,2002.0,2,534
23,5,1976,1976,0.0,1040,1060,1060,1,6,1,1976.0,2,572
24,5,1968,2001,0.0,1060,1060,1060,1,6,1,1968.0,1,270
25,8,2007,2007,640.0,1566,1600,1600,2,7,1,2007.0,3,890
26,5,1951,2000,0.0,900,900,900,1,5,0,2005.0,2,576
27,8,2007,2008,200.0,1704,1704,1704,2,7,1,2008.0,3,772
28,5,1957,1997,0.0,1484,1600,1600,1,6,2,1957.0,1,319
29,4,1927,1950,0.0,520,520,520,1,4,0,1920.0,1,240
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,5,2005,2005,0.0,732,734,1838,2,7,1,2005.0,2,372
1431,6,1976,1976,0.0,958,958,958,2,5,0,1976.0,2,440
1432,4,1927,2007,0.0,656,968,968,2,5,0,1928.0,1,216
1433,6,2000,2000,318.0,936,962,1792,2,8,1,2000.0,2,451
1434,5,1977,1977,0.0,1126,1126,1126,2,5,1,1977.0,2,484
1435,6,1962,2005,237.0,1319,1537,1537,1,7,1,1962.0,2,462
1436,4,1971,1971,0.0,864,864,864,1,5,0,1974.0,2,528
1437,8,2008,2008,426.0,1932,1932,1932,2,7,1,2008.0,3,774
1438,6,1957,1996,0.0,912,1236,1236,1,6,0,1957.0,2,923
1439,7,1979,1979,96.0,539,1040,1725,2,6,1,1979.0,2,550
1440,6,1922,1994,0.0,588,1423,2555,2,11,1,1993.0,2,672
1441,6,2004,2004,147.0,848,848,848,1,3,1,2004.0,2,420
1442,10,2008,2008,160.0,1017,1026,2007,2,10,1,2008.0,3,812
1443,6,1916,1950,0.0,952,952,952,1,4,1,1916.0,1,192
1444,7,2004,2004,106.0,1422,1422,1422,2,7,0,2004.0,2,626
1445,6,1966,1966,0.0,814,913,913,1,6,0,1990.0,1,240
1446,5,1962,1962,189.0,1188,1188,1188,1,6,0,1962.0,1,312
1447,8,1995,1996,438.0,1220,1220,2090,2,8,1,1995.0,2,556
1448,4,1910,2000,0.0,560,796,1346,1,6,0,1950.0,1,384
1449,5,1970,1970,0.0,630,630,630,1,3,0,2005.0,0,0
1450,5,1974,1974,0.0,896,896,1792,2,8,0,2005.0,0,0
1451,8,2008,2009,194.0,1573,1578,1578,2,7,1,2008.0,3,840
1452,5,2005,2005,80.0,547,1072,1072,1,5,0,2005.0,2,525
1453,5,2006,2006,0.0,1140,1140,1140,1,6,0,2005.0,0,0
1454,7,2004,2005,0.0,1221,1221,1221,2,6,0,2004.0,2,400
1455,6,1999,2000,0.0,953,953,1647,2,7,1,1999.0,2,460
1456,6,1978,1988,119.0,1542,2073,2073,2,7,2,1978.0,2,500
1457,7,1941,2006,0.0,1152,1188,2340,2,9,2,1941.0,1,252
1458,5,1950,1996,0.0,1078,1078,1078,1,5,0,1950.0,1,240
1459,5,1965,1965,0.0,1256,1256,1256,1,6,0,1965.0,1,276

In [98]:
X_test = pd.read_csv('test.csv')

In [99]:
#Y3 = Model2.predict(X_test)
X_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [101]:
cols.remove('SalePrice')

In [102]:
cols

['OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'TotalBsmtSF',
 '1stFlrSF',
 'GrLivArea',
 'FullBath',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea']

In [103]:
X_test1 = X_test[cols]

In [105]:
X_test1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 13 columns):
OverallQual     1459 non-null int64
YearBuilt       1459 non-null int64
YearRemodAdd    1459 non-null int64
MasVnrArea      1444 non-null float64
TotalBsmtSF     1458 non-null float64
1stFlrSF        1459 non-null int64
GrLivArea       1459 non-null int64
FullBath        1459 non-null int64
TotRmsAbvGrd    1459 non-null int64
Fireplaces      1459 non-null int64
GarageYrBlt     1381 non-null float64
GarageCars      1458 non-null float64
GarageArea      1458 non-null float64
dtypes: float64(5), int64(8)
memory usage: 148.3 KB

In [109]:
X_test1.isna().any()

OverallQual     False
YearBuilt       False
YearRemodAdd    False
MasVnrArea       True
TotalBsmtSF      True
1stFlrSF        False
GrLivArea       False
FullBath        False
TotRmsAbvGrd    False
Fireplaces      False
GarageYrBlt      True
GarageCars       True
GarageArea       True
dtype: bool

In [107]:
X_test1 = X_test1.copy()

In [108]:
X_test1['GarageYrBlt'].fillna(value=X_test1['GarageYrBlt'].mode(),inplace=True)

In [112]:
sum(X_test1['MasVnrArea'].isna())

15

In [126]:
X_test1['MasVnrArea'].fillna(value=0.0,inplace=True)

In [141]:
X_test1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 13 columns):
OverallQual     1459 non-null int64
YearBuilt       1459 non-null int64
YearRemodAdd    1459 non-null int64
MasVnrArea      1459 non-null float64
TotalBsmtSF     1459 non-null float64
1stFlrSF        1459 non-null int64
GrLivArea       1459 non-null int64
FullBath        1459 non-null int64
TotRmsAbvGrd    1459 non-null int64
Fireplaces      1459 non-null int64
GarageYrBlt     1459 non-null float64
GarageCars      1459 non-null float64
GarageArea      1459 non-null float64
dtypes: float64(5), int64(8)
memory usage: 148.3 KB

In [121]:
X_test1[X_test1['GarageYrBlt'].isna()==True]['GarageYrBlt']=2005.0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [139]:
X_test1['GarageArea'].mean()

472.76886145404666

In [131]:
X_test1['TotalBsmtSF'].fillna(value=1046.1179698,inplace=True)

In [133]:
X_test1['GarageYrBlt'].fillna(value=2005.0,inplace=True)

In [137]:
X_test1['GarageCars'].fillna(value=2.0,inplace=True)

In [140]:
X_test1['GarageArea'].fillna(value=472.76886,inplace=True)

In [142]:
Y_3 = model2.predict(X_test1)

In [157]:
df_op3 = X_test.iloc[:,0]

In [160]:
X_test['SalePrice'] = Y_3

In [159]:
type(df_op3)

pandas.core.series.Series

In [153]:
Y_3[:]

array([109500, 145000, 181000, ..., 154000, 136500, 219500], dtype=int64)

In [162]:
X_test[['Id','SalePrice']].to_csv('output3.csv',index=False)

In [24]:
df = pd.read_csv('train.csv')

In [31]:
cat_features = df.dtypes[df.dtypes=='object'].index

In [32]:
X

,OverallQual,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageCars,GarageArea
0,7,2003,2003,856,856,1710,2,8,2,548
1,6,1976,1976,1262,1262,1262,2,6,2,460
2,7,2001,2002,920,920,1786,2,6,2,608
3,7,1915,1970,756,961,1717,1,7,3,642
4,8,2000,2000,1145,1145,2198,2,9,3,836
5,5,1993,1995,796,796,1362,1,5,2,480
6,8,2004,2005,1686,1694,1694,2,7,2,636
7,7,1973,1973,1107,1107,2090,2,7,2,484
8,7,1931,1950,952,1022,1774,2,8,2,468
9,5,1939,1950,991,1077,1077,1,5,1,205
10,5,1965,1965,1040,1040,1040,1,5,1,384
11,9,2005,2006,1175,1182,2324,3,11,3,736
12,5,1962,1962,912,912,912,1,4,1,352
13,7,2006,2007,1494,1494,1494,2,7,3,840
14,6,1960,1960,1253,1253,1253,1,5,1,352
15,7,1929,2001,832,854,854,1,5,2,576
16,6,1970,1970,1004,1004,1004,1,5,2,480
17,4,1967,1967,0,1296,1296,2,6,2,516
18,5,2004,2004,1114,1114,1114,1,6,2,576
19,5,1958,1965,1029,1339,1339,1,6,1,294
20,8,2005,2006,1158,1158,2376,3,9,3,853
21,7,1930,1950,637,1108,1108,1,6,1,280
22,8,2002,2002,1777,1795,1795,2,7,2,534
23,5,1976,1976,1040,1060,1060,1,6,2,572
24,5,1968,2001,1060,1060,1060,1,6,1,270
25,8,2007,2007,1566,1600,1600,2,7,3,890
26,5,1951,2000,900,900,900,1,5,2,576
27,8,2007,2008,1704,1704,1704,2,7,3,772
28,5,1957,1997,1484,1600,1600,1,6,1,319
29,4,1927,1950,520,520,520,1,4,1,240
...,...,...,...,...,...,...,...,...,...,...
1430,5,2005,2005,732,734,1838,2,7,2,372
1431,6,1976,1976,958,958,958,2,5,2,440
1432,4,1927,2007,656,968,968,2,5,1,216
1433,6,2000,2000,936,962,1792,2,8,2,451
1434,5,1977,1977,1126,1126,1126,2,5,2,484
1435,6,1962,2005,1319,1537,1537,1,7,2,462
1436,4,1971,1971,864,864,864,1,5,2,528
1437,8,2008,2008,1932,1932,1932,2,7,3,774
1438,6,1957,1996,912,1236,1236,1,6,2,923
1439,7,1979,1979,539,1040,1725,2,6,2,550
1440,6,1922,1994,588,1423,2555,2,11,2,672
1441,6,2004,2004,848,848,848,1,3,2,420
1442,10,2008,2008,1017,1026,2007,2,10,3,812
1443,6,1916,1950,952,952,952,1,4,1,192
1444,7,2004,2004,1422,1422,1422,2,7,2,626
1445,6,1966,1966,814,913,913,1,6,1,240
1446,5,1962,1962,1188,1188,1188,1,6,1,312
1447,8,1995,1996,1220,1220,2090,2,8,2,556
1448,4,1910,2000,560,796,1346,1,6,1,384
1449,5,1970,1970,630,630,630,1,3,0,0
1450,5,1974,1974,896,896,1792,2,8,0,0
1451,8,2008,2009,1573,1578,1578,2,7,3,840
1452,5,2005,2005,547,1072,1072,1,5,2,525
1453,5,2006,2006,1140,1140,1140,1,6,0,0
1454,7,2004,2005,1221,1221,1221,2,6,2,400
1455,6,1999,2000,953,953,1647,2,7,2,460
1456,6,1978,1988,1542,2073,2073,2,7,2,500
1457,7,1941,2006,1152,1188,2340,2,9,1,252
1458,5,1950,1996,1078,1078,1078,1,5,1,240
1459,5,1965,1965,1256,1256,1256,1,6,1,276